### ISSUE TITLE
LineageOS AOPT Incompatibility

### ISSUE THREAD

**Issue by thewan056** [PitchedApps/Material-Glass-Substratum#7]
Hi do you mind releasing  just the whatsapp semi-transparent chat bubble seperately? I love semi-transparent chat bubbles which helps to flesh out the chat wallpaper behind. Since the rest of the whatsapp theme seems broken besides the chat bubble, I hope you could do that, thank you.

**Comment by AllanWang** [comment]
@thewan056 I will try to release a build within a few days to fix whatsapp since that's been the most mentioned issue

**Comment by thewan056** [comment]
If you plan to fix the whatsapp theme, then that is fine as well. And there is no need to rush with fixing it.

I just thought maybe you planned to abandon the Whatsapp theme, which is why I made the request. 

Thanks for the reply and keep up the good work

**Comment by AllanWang** [comment]
@thewan056 

can you download [this](https://github.com/PitchedApps/Material-Glass-Test-Builds/releases/tag/v101) test build and tell me if it fixes the chat? (screenshot would be nice). I don't use whatsapp so I don't have any conversations to test.

I know the toolbars and such still have black text but I will be working on that.

That test apk can be installed alongside the original

**Comment by thewan056** [comment]
edit: deleted screenshot. if needed, just ask again.

@AllanWang Looks way better now, but the button next to the chatbox, which is the mic button in the above screenshot, doesn't seem to be aligned with its border I think (Sorry my current wallpaper makes it kind of hard to see). This affects all of those kind of buttons, like the new message button on the main page, etc.

update: The Unread Message separator line in the chat window is black text on black background which makes it hard to read.

**Comment by AllanWang** [comment]
Okay ill try to figure that out. For the mic button, that's sometimes typical of transparent themes. The shadows are very prominent and I think that's the issue with the white circle. It should be aligned though since themes usually don't touch layouts.

**Comment by AllanWang** [comment]
@thewan056 
[Release 128](https://github.com/PitchedApps/Material-Glass-Test-Builds/releases/tag/v128) further fixes the chat colors. This one was a big change so I'm letting you know, but in the future, feel free to look on xda or just have a look at the test builds to keep up with it. Let me know if any of the black texts were fixed or if new ones are still there, since I don't really use the app and don't have many messages to test with

**Comment by thewan056** [comment]
» [com.whatsapp]: /data/user/0/projekt.substratum/cache/SubstratumBuilder//res/layout-v21/conversation_entry.xml:9: error: Error: No resource found that matches the given name (at 'background' with value '@*com.whatsapp:drawable/input').
» [com.whatsapp]: /data/user/0/projekt.substratum/cache/SubstratumBuilder//res/layout-v21/conversation_entry.xml:16: error: Error: No resource found that matches the given name (at 'src' with value '@*com.whatsapp:drawable/input_cam').
» [com.whatsapp]: /data/user/0/projekt.substratum/cache/SubstratumBuilder//res/layout-v21/conversation_entry.xml:32: error: Error: No resource found that matches the given name (at 'layout_marginRight' with value '@*com.whatsapp:dimen/input_layout_voice_animation_margin').
» [com.whatsapp]: /data/user/0/projekt.substratum/cache/SubstratumBuilder//res/layout-v21/conversation_entry.xml:32: error: Error: No resource found that matches the given name (at 'layout_marginBottom' with value '@*com.whatsapp:dimen/input_layout_voice_animation_margin').
» [com.whatsapp]: Installation of "com.whatsapp" has failed.

@AllanWang couldnt apply Release 128. Error as above. Note I didnt test the whole theme, just the whatsapp overlay. Also I am running in legacy RRO mode if that affects anything.

**Comment by AllanWang** [comment]
that's weird. I tested this on my other phone which uses legacy. Is your app updated though?

**Comment by thewan056** [comment]
You mean my whatsapp? I am on the beta and it just recently updated to 2.17.218. Should I revert back to
stable and try again?

**Comment by AllanWang** [comment]
No for substratum. It seems like you can't use package attributes. Which device and android version?

**Comment by thewan056** [comment]
I'm on a Xiaomi Mi Note running Lineage 14.1 and Android 7.1.2. my substratum version is 731, last updated on 20th May. 

Edit: LOS version 20170519 if it helps.

**Comment by AllanWang** [comment]
Can you try applying the overlay again and then send us a full log? You can use an app like [Matlog](https://play.google.com/store/apps/details?id=com.pluscubed.matlog&hl=en).

Clear the log before applying and make sure nothing private is sent.

**Comment by thewan056** [comment]
[2017-06-07-02-40-24mgtest.txt](https://github.com/PitchedApps/Material-Glass-Substratum/files/1056096/2017-06-07-02-40-24mgtest.txt)

Never sent a logcat before so I hope I'm doing this right.

**Comment by AllanWang** [comment]
@thewan056 can you try opting out of beta and installing the latest stable version? Or you can give me the apk you are using so I can see if the resources are actually there

**Comment by thewan056** [comment]
Here's the version I'm currently on. https://www.apkmirror.com/apk/whatsapp-inc/whatsapp/whatsapp-2-17-218-release/

I can confirm that this a problem with the beta. I've opted out of beta and reinstalled the latest stable version (2.17.190) and can confirm that the whatsapp overlay now works.

**Comment by thewan056** [comment]
On the whatsapp theme itself, I would say it looks really good now. Nearly perfect. Just the issue of black text on black background for the mentioned Unread Message seperator, security code changed, added to group, stuff like that. Makes it hard to read on certain wallpapers, but not a big issue since most don't pay attention to those.

**Comment by thewan056** [comment]
@AllanWang 
Stable whatsapp just updated to 2.17.223 and the latest Whatsapp overlay has now stopped working.

**Comment by AllanWang** [comment]
@thewan056 that's going to be a common occurrence now for whatsapp since I need to do extra things to theme it. I'll get another build out within a few days.

**Comment by AllanWang** [comment]
@thewan056 try [v149](https://github.com/PitchedApps/Material-Glass-Test-Builds/releases/tag/v149)
I now generate full builds and deltas so if you only want one apk, go with the full one.
I'm closing this issue, but if there's ever a problem with whatsapp, feel free to reply here or create a new issue.
